<?php
	$title = "Privacy Policy";
    include('header.php');
?>
<div style="text-align:left;">
  <h2>Privacy Policy</h2>

<p>When accessing our Website, LectureBank will learn certain information about you during your visit. How we will handle information we learn about you depends upon what you do when visiting our site.</p>

<p>If you visit our site to read or download information on our pages, we collect and store only the following information about you:</p>

<p>1. The name of the domain from which you access the Internet<br />2. The date and time you access our site<br />3. The Internet address of the website you used to link directly to our site.<br />4. First Name<br />5. Last Name<br />6. Home Address<br />7. Work Address<br />8. Telephone Number<br />9. Email Address<br />10. Undergraduate Institution(s)<br />11. Graduate Institution(s)<br />12. Postdoctoral Institution(s)<br />13. Professional Qualifications<br />14. Field of Study<br />15. Fields of Interest<br />16. Concentration Tags<br />17. Publication Citations<br />18. Publication Abstracts<br />19. Publication Tags<br />20. Talk Abstracts<br />21. Talk Tags<br />22. Collaborators and Other Affiliations<br />23. Events (Including, But Not Limited to Conferences, Symposia, and Seminars) Invited To, Attended, and Spoken At</p>

<p>If you identify yourself by sending us an e-mail containing personal information, then the information collected will be solely used to respond to your message.</p>

<p>The information collected is for statistical purposes. LectureBank may use software programs to create summary statistics, which are used for such purposes as assessing the number of visitors to the different sections of our site, what information is of most and least interest, determining technical design specifications, and identifying system performance or problem areas.</p>

<p>For site security purposes and to ensure that this service remains available to all users, LectureBank uses software programs to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage.</p>

<p>LectureBank will not obtain personally-identifying information about you when you visit our site, unless you choose to provide such information to us, nor will such information be sold or otherwise transferred to unaffiliated third parties without the approval of the user at the time of collection.</p>

<p>Generated by: <a target="_blank" title="Northern Virginia Business Attorneys and Lawyers" href="http://www.generalcounsellaw.com">General Counsel, PC</a> and <a target="_blank" title="Small Business Attorneys and Lawyers" href="http://www.LegalRiver.com">Legal River</a>'s <a target="_blank" title="Privacy Policy Generator" href="http://privacy-policy-generator.legalriver.com">Privacy Policy Generator</a></p>
</div>
<?php
	include('footer.php');
?>